Update  Kyverno.yaml

diff --git a/.github/workflows/ Kyverno.yaml b/.github/workflows/ Kyverno.yaml
--- a/.github/workflows/ Kyverno.yaml
+++ b/.github/workflows/ Kyverno.yaml
@@ -337,108 +337,103 @@ jobs:
         cosign verify-attestation --certificate-github-workflow-name=.github/workflows/cicd.yml@refs/heads/testing --certificate-github-workflow-ref=refs/heads/testing --certificate-github-workflow-repository=https://github.com/dheeman2912/spring-petclinic --certificate-github-workflow-trigger=push --key cosign.pub ghcr.io/dheeman2912/spring-petclinic@${{ needs.build-and-scan.outputs.image_sha }} | jq -r .payload | base64 --decode | jq . || { echo "Error: Predicate attestation verification failed"; exit 1; }
       shell: bash
 
-  # Deploy_To_Aks:
-  #   runs-on: ubuntu-latest
-  #   container:
-  #     image:  dheeman29/new_image:v3
-  #   needs: Attest_Verify_Predicate
-  #   steps:
-  #     # Step 1: Capture SHA256 ID of the Image
-  #     - name: Capture SHA256 ID of the Image
-  #       run: |          
-  #         REPO_DIGESTS=$(docker inspect --format='{{.RepoDigests}}'  dheeman29/new_image:v3) 
-  #         if [ "$REPO_DIGESTS" == "[]" ]; then
-  #           echo "Error: RepoDigests is empty. Cannot retrieve SHA256."
-  #           exit 1
-  #         fi
-  #         CONTAINER_SHA256=$(docker inspect --format='{{index .RepoDigests 0}}'  dheeman29/new_image:v3| sed 's/.*@sha256://')
-  #         echo "CONTAINER_SHA256=$CONTAINER_SHA256" >> $GITHUB_ENV
+  Deploy_To_Aks:
+    runs-on: ubuntu-latest
+    container:
+      image:  dheeman29/new_image:v3
+    needs: Attest_Verify_Predicate
+    steps:
+      # Step 1: Capture SHA256 ID of the Image
+      - name: Capture SHA256 ID of the Image
+        run: |          
+          REPO_DIGESTS=$(docker inspect --format='{{.RepoDigests}}'  dheeman29/new_image:v3) 
+          if [ "$REPO_DIGESTS" == "[]" ]; then
+            echo "Error: RepoDigests is empty. Cannot retrieve SHA256."
+            exit 1
+          fi
+          CONTAINER_SHA256=$(docker inspect --format='{{index .RepoDigests 0}}'  dheeman29/new_image:v3| sed 's/.*@sha256://')
+          echo "CONTAINER_SHA256=$CONTAINER_SHA256" >> $GITHUB_ENV
 
-  #     # Step 2: Verify Container SHA256 ID        
-  #     - name: Verify Container SHA256 ID        
-  #       run: |          
-  #         EXPECTED_SHA256="${{ secrets.EXPECTED_SHA256 }}"
-  #         ACTUAL_SHA256="${{ env.CONTAINER_SHA256 }}"
+      # Step 2: Verify Container SHA256 ID        
+      - name: Verify Container SHA256 ID        
+        run: |          
+          EXPECTED_SHA256="${{ secrets.EXPECTED_SHA256 }}"
+          ACTUAL_SHA256="${{ env.CONTAINER_SHA256 }}"
           
-  #         if [ "$EXPECTED_SHA256" != "$ACTUAL_SHA256" ]; then
-  #           echo "SHA256 mismatch. Aborting."
-  #           exit 1
-  #         fi
-  #         echo "SHA256 ID verified successfully."
+          if [ "$EXPECTED_SHA256" != "$ACTUAL_SHA256" ]; then
+            echo "SHA256 mismatch. Aborting."
+            exit 1
+          fi
+          echo "SHA256 ID verified successfully."
 
-  #     # Step 3: Checkout the code
-  #     - name: Checkout Code
-  #       uses: actions/checkout@v4
-  #       with:
-  #         fetch-depth: 0  # Shallow clones should be disabled for better relevancy of analysis
+      # Step 3: Checkout the code
+      - name: Checkout Code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0  # Shallow clones should be disabled for better relevancy of analysis
 
-  #     # Step 4: Clean up faulty Azure CLI sources
-  #     - name: Clean up faulty Azure CLI sources
-  #       run: |
-  #         rm -f /etc/apt/sources.list.d/azure-cli.list
-  #         rm -f /etc/apt/sources.list.d/azure-cli.sourcess
+           # Step 6: Login to Azure
+      - name: Login to Azure
+        uses: azure/login@v1
+        with:
+          creds: ${{ secrets.AZURE_CREDENTIALS }}
+          continue-on-error: true
+      - name: Check Azure Login Status
+        run: |
+         if [ $? -eq 0 ]; then
+          echo "Successfully logged in to Azure."
+         else
+          echo "Error: Azure login failed."
+          exit 1
+         fi
 
-  #     # Step 5: Install Azure CLI
-  #     - name: Install Azure CLI
-  #       run: |
-  #         apt-get update
-  #         apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release unzip
-  #         curl -sL https://aka.ms/InstallAzureCLIDeb | bash
-          
-  #         # Install kubectl
-  #         curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
-  #         install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
-  #         rm kubectl  # Clean up after installation
+    # Step 7: Set up kubeconfig for AKS access
+      - name: Set up kubeconfig for AKS access
+        run: |
+         echo "${{ secrets.KUBECONFIG_FILE }}" | base64 -d > ~/.kube/config
+         chmod 600 ~/.kube/config
+         if ! kubectl version --client; then
+          echo "Error: kubectl not found or not configured correctly"
+          exit 1
+         fi
+         echo "Kubeconfig set up successfully."
 
-  #     # Step 6: Login to Azure
-  #     - name: Login to Azure
-  #       uses: azure/login@v1
-  #       with:
-  #         creds: ${{ secrets.AZURE_CREDENTIALS }}
+    # Step 8: Verify the AKS Cluster via Managed Identity
+      - name: Verify the AKS Cluster via Managed Identity
+        run: |
+         CLUSTER_MANAGED_ID=$(az aks show --resource-group ${{ secrets.RESOURCE_GROUP }} --name ${{ secrets.CLUSTER_NAME }} --query identity.principalId --output tsv) || { echo "Failed to fetch Managed Identity"; exit 1; }
+        
+         EXPECTED_MANAGED_ID="${{ secrets.EXPECTED_MANAGED_ID }}"
+        
+         if [[ "$EXPECTED_MANAGED_ID" != "$CLUSTER_MANAGED_ID" ]]; then
+          echo "Error: Managed Identity does not match. Aborting deployment."
+          exit 1
+         else
+          echo "Managed Identity verified successfully."
+         fi
 
-  #     # Step 7: Run Azure CLI commands to get credentials
-  #     - name: Get AKS credentials
-  #       run: |
-  #         az account show
-  #         az aks get-credentials --resource-group ${{ secrets.RESOURCE_GROUP }} --name ${{ secrets.CLUSTER_NAME }}
+    # Step 9: Apply Kyverno Policy
+      - name: Apply Kyverno Policy
+        run: |
+         if kubectl apply -f K8s/kyverno-policy-with-key.yaml; then
+          echo "Kyverno policy applied successfully."
+         else
+          echo "Error applying Kyverno policy."
+          exit 1
+         fi
 
-  #     # Step 8: Set up kubelogin for non-interactive login
-  #     - name: Set up kubelogin
-  #       uses: azure/use-kubelogin@v1
-  #       with:
-  #         kubelogin-version: 'v0.0.25'
-
-  #     # Step 9: Retrieve Kubernetes context
-  #     - name: Get K8s context
-  #       uses: azure/aks-set-context@v3
-  #       with:
-  #         resource-group: ${{ secrets.RESOURCE_GROUP }}
-  #         cluster-name: ${{ secrets.CLUSTER_NAME }}
-  #         admin: 'false'
-  #         use-kubelogin: 'true'
-          
-  #     # Step 10: Verify the AKS Cluster via Managed Identity of the cluster
-  #     - name: Verify the AKS Cluster via Managed Identity
-  #       run: |
-  #         CLUSTER_MANAGED_ID=$(az aks show --resource-group ${{ secrets.RESOURCE_GROUP }} --name ${{ secrets.CLUSTER_NAME }} --query identity.principalId --output tsv)
-  #         echo "CLUSTER_MANAGED_ID=$CLUSTER_MANAGED_ID" >> $GITHUB_ENV
-
-  #         EXPECTED_MANAGED_ID="${{ secrets.EXPECTED_MANAGED_ID }}"
-          
-  #         if [[ "$EXPECTED_MANAGED_ID" != "$CLUSTER_MANAGED_ID" ]]; then
-  #           echo "Error: Managed Identity does not match. Aborting deployment."
-  #           exit 1
-  #         else
-  #           echo "Managed Identity verified successfully."
-  #         fi
-      
-          
-  #     - name: Apply Kyverno Policy
-  #       run: |
-  #         kubectl apply -f K8s/kyverno-policy-with-key.yaml
-          
-  #     # Step 11: Deploy to AKS
-  #     - name: Deploy to AKS
-  #       run: |
-  #         kubectl apply -f K8s/deployment.yaml
-  #         kubectl apply -f K8s/service.yaml
+    # Step 10: Deploy to AKS
+      - name: Deploy to AKS
+        run: |
+         if kubectl apply -f K8s/deployment.yaml; then
+          echo "Deployment applied successfully."
+         else
+          echo "Error deploying application."
+          exit 1
+         fi
+         if kubectl apply -f K8s/service.yaml; then
+          echo "Service applied successfully."
+         else
+          echo "Error deploying service."
+          exit 1
+         fi
