Update  Kyverno.yaml

diff --git a/.github/workflows/ Kyverno.yaml b/.github/workflows/ Kyverno.yaml
--- a/.github/workflows/ Kyverno.yaml
+++ b/.github/workflows/ Kyverno.yaml
@@ -247,8 +247,12 @@ jobs:
      - name: Extract Commit ID
        id: extract_commit_id
        run: |
-          COMMIT_ID=$(jq -r '.commit_id' output.json)
+          # Print output.json content for debugging
+          cat output.json
+          # Extract commit_id and check for errors
+          COMMIT_ID=$(jq -r '.commit_id' output.json) || { echo "Failed to extract commit_id"; exit 1; }
           echo "COMMIT_ID=$COMMIT_ID" >> $GITHUB_ENV
+          echo "Extracted Commit ID: $COMMIT_ID"  # Debug output to confirm extraction
          
 
   Attest_Verify_Predicate:
