Update cicd.yml

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -184,88 +184,88 @@ jobs:
           COSIGN_KEY: ${{secrets.COSIGN_KEY}}
           COSIGN_PASSWORD: ${{secrets.COSIGN_PASSPHRASE}}
         
-      - name: Verify Docker Image Signature
-        run: |
-          cosign verify --key cosign.pub ghcr.io/sachinmaniyar/${{ env.AppName }}:latest | jq . #--insecure-ignore-tlog #--check-claims=false
-      - name: Attach SBOM
-        id: attach-sbom
-        run: |
-          set -e  # Exit on error
-          # Run the cosign attach sbom command and capture its output
-          output=$(cosign attach sbom --sbom sbom.json ghcr.io/sachinmaniyar/${{ env.AppName }}:latest 2>&1) || { echo "Failed to run cosign attach sbom"; exit 1; }
-          echo "cat output --> showing output below"
-          echo "output: $output"
-          # Extract the SHA from the output
-          sbom_filename=$(echo "$output" | grep -oP 'sha256-[\w\d]+\.sbom') || { echo "Failed to extract SBOM filename"; exit 1; }
-          echo "sbom_filename: $sbom_filename"
-          # Check if the extraction was successful
-          if [ -z "$sbom_filename" ]; then
-            echo "Error: No SBOM filename found in the output"
-            exit 1
-          fi
-          # Set the extracted SHA as an environment variable
-          echo "SBOM_FILENAME=$sbom_filename" >> $GITHUB_ENV
-      - name: Sign the SBOM attached with the Image
-        run: |
-          set -e  # Exit on error
-          # Use the environment variable to construct the command
-          if [ -z "$SBOM_FILENAME" ]; then
-            echo "Error: SBOM_FILENAME environment variable is not set"
-            exit 1
-          fi
-          echo "Signing SBOM with filename: $SBOM_FILENAME"
-          cosign sign --key env://COSIGN_KEY ghcr.io/sachinmaniyar/${{ env.AppName }}:$SBOM_FILENAME --yes || { echo "Failed to sign with SBOM"; exit 1; }
-        shell: bash
-        env:
-          COSIGN_KEY: ${{secrets.COSIGN_KEY}}
-          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSPHRASE}}
+      # - name: Verify Docker Image Signature
+      #   run: |
+      #     cosign verify --key cosign.pub ghcr.io/sachinmaniyar/${{ env.AppName }}:latest | jq . #--insecure-ignore-tlog #--check-claims=false
+      # - name: Attach SBOM
+      #   id: attach-sbom
+      #   run: |
+      #     set -e  # Exit on error
+      #     # Run the cosign attach sbom command and capture its output
+      #     output=$(cosign attach sbom --sbom sbom.json ghcr.io/sachinmaniyar/${{ env.AppName }}:latest 2>&1) || { echo "Failed to run cosign attach sbom"; exit 1; }
+      #     echo "cat output --> showing output below"
+      #     echo "output: $output"
+      #     # Extract the SHA from the output
+      #     sbom_filename=$(echo "$output" | grep -oP 'sha256-[\w\d]+\.sbom') || { echo "Failed to extract SBOM filename"; exit 1; }
+      #     echo "sbom_filename: $sbom_filename"
+      #     # Check if the extraction was successful
+      #     if [ -z "$sbom_filename" ]; then
+      #       echo "Error: No SBOM filename found in the output"
+      #       exit 1
+      #     fi
+      #     # Set the extracted SHA as an environment variable
+      #     echo "SBOM_FILENAME=$sbom_filename" >> $GITHUB_ENV
+      # - name: Sign the SBOM attached with the Image
+      #   run: |
+      #     set -e  # Exit on error
+      #     # Use the environment variable to construct the command
+      #     if [ -z "$SBOM_FILENAME" ]; then
+      #       echo "Error: SBOM_FILENAME environment variable is not set"
+      #       exit 1
+      #     fi
+      #     echo "Signing SBOM with filename: $SBOM_FILENAME"
+      #     cosign sign --key env://COSIGN_KEY ghcr.io/sachinmaniyar/${{ env.AppName }}:$SBOM_FILENAME --yes || { echo "Failed to sign with SBOM"; exit 1; }
+      #   shell: bash
+      #   env:
+      #     COSIGN_KEY: ${{secrets.COSIGN_KEY}}
+      #     COSIGN_PASSWORD: ${{secrets.COSIGN_PASSPHRASE}}
         
 
-      - name: Verify Sign of SBOM attached with the Image
-        run: |
-          set -e  # Exit on error
-          cosign verify --key cosign.pub ghcr.io/sachinmaniyar/${{ env.AppName }}:$SBOM_FILENAME | jq . || { echo "Failed to verify SBOM Sign"; exit 1; }
-      - name: Directly attest SBOM with the Image
-        run: |
-          set -e  # Exit on error
-          output=$(cosign attest --key env://COSIGN_KEY --predicate sbom.json ghcr.io/sachinmaniyar/${{ env.AppName }}:latest --yes 2>&1) || { echo "Failed to attest sbom with the image"; exit 1; }
-          echo "output: $output"
-        shell: bash
+      # - name: Verify Sign of SBOM attached with the Image
+      #   run: |
+      #     set -e  # Exit on error
+      #     cosign verify --key cosign.pub ghcr.io/sachinmaniyar/${{ env.AppName }}:$SBOM_FILENAME | jq . || { echo "Failed to verify SBOM Sign"; exit 1; }
+      # - name: Directly attest SBOM with the Image
+      #   run: |
+      #     set -e  # Exit on error
+      #     output=$(cosign attest --key env://COSIGN_KEY --predicate sbom.json ghcr.io/sachinmaniyar/${{ env.AppName }}:latest --yes 2>&1) || { echo "Failed to attest sbom with the image"; exit 1; }
+      #     echo "output: $output"
+      #   shell: bash
 
-        env:
-          COSIGN_KEY: ${{secrets.COSIGN_KEY}}
-          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSPHRASE}}
+      #   env:
+      #     COSIGN_KEY: ${{secrets.COSIGN_KEY}}
+      #     COSIGN_PASSWORD: ${{secrets.COSIGN_PASSPHRASE}}
       
-      - name: Verfiy the attested Image
-        run: |
-          set -e  # Exit on error
+      # - name: Verfiy the attested Image
+      #   run: |
+      #     set -e  # Exit on error
           
-          output1=$(cosign verify-attestation --key cosign.pub ghcr.io/sachinmaniyar/${{ env.AppName }}:latest | jq . 2>&1) || { echo "Failed to verify the attested image"; exit 1; }
-          echo "output: $output1"
-      - name: Sign SBOM
-        run: |
-          # set -e  # Exit on error
-          cosign sign-blob --yes --key env://COSIGN_KEY sbom.json --bundle cosign.bundle 2>&1 #| jq -r .payload | base64 --decode | jq . 2>&1 #|| { echo "Failed to sign the blob"; exit 1; }
-        shell: bash
-        env:
-          COSIGN_KEY: ${{secrets.COSIGN_KEY}}
-          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSPHRASE}}
+      #     output1=$(cosign verify-attestation --key cosign.pub ghcr.io/sachinmaniyar/${{ env.AppName }}:latest | jq . 2>&1) || { echo "Failed to verify the attested image"; exit 1; }
+      #     echo "output: $output1"
+      # - name: Sign SBOM
+      #   run: |
+      #     # set -e  # Exit on error
+      #     cosign sign-blob --yes --key env://COSIGN_KEY sbom.json --bundle cosign.bundle 2>&1 #| jq -r .payload | base64 --decode | jq . 2>&1 #|| { echo "Failed to sign the blob"; exit 1; }
+      #   shell: bash
+      #   env:
+      #     COSIGN_KEY: ${{secrets.COSIGN_KEY}}
+      #     COSIGN_PASSWORD: ${{secrets.COSIGN_PASSPHRASE}}
 
-      - name: upload Signed SBOM to Github Registry
-        run: |
-          # set -e  # Exit on error
-          output2=$(cosign upload blob -f cosign.bundle ghcr.io/sachinmaniyar/${{ env.AppName }}:latest 2>&1) #| jq .) #|| { echo "Failed to upload the blob to the Registry"; exit 1; }
-          echo "output: $output2"
-          sbom_file=$(echo "$output2" | grep -oP 'sha256:[\w\d]{64}' | head -n 1) || { echo "Failed to extract SBOM filename"; exit 1; }
-          echo "sbom_file: $sbom_file"
-      - name: Verify SBOM Uploaded to Image Repo
-        run: |
+      # - name: upload Signed SBOM to Github Registry
+      #   run: |
+      #     # set -e  # Exit on error
+      #     output2=$(cosign upload blob -f cosign.bundle ghcr.io/sachinmaniyar/${{ env.AppName }}:latest 2>&1) #| jq .) #|| { echo "Failed to upload the blob to the Registry"; exit 1; }
+      #     echo "output: $output2"
+      #     sbom_file=$(echo "$output2" | grep -oP 'sha256:[\w\d]{64}' | head -n 1) || { echo "Failed to extract SBOM filename"; exit 1; }
+      #     echo "sbom_file: $sbom_file"
+      # - name: Verify SBOM Uploaded to Image Repo
+      #   run: |
           
-          cosign verify-blob sbom.json --bundle cosign.bundle --certificate-github-workflow-name=.github/workflows/cicd.yml@refs/heads/testing --certificate-github-workflow-ref=refs/heads/main --certificate-github-workflow-repository=https://github.com/sachinmaniyar/${{ env.AppName }} --certificate-github-workflow-trigger=push --key cosign.pub 2>&1 #| jq -r .payload | base64 --decode | jq .
-        shell: bash
-        env:
-          COSIGN_KEY: ${{secrets.COSIGN_KEY}}
-          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSPHRASE}}
+      #     cosign verify-blob sbom.json --bundle cosign.bundle --certificate-github-workflow-name=.github/workflows/cicd.yml@refs/heads/testing --certificate-github-workflow-ref=refs/heads/main --certificate-github-workflow-repository=https://github.com/sachinmaniyar/${{ env.AppName }} --certificate-github-workflow-trigger=push --key cosign.pub 2>&1 #| jq -r .payload | base64 --decode | jq .
+      #   shell: bash
+      #   env:
+      #     COSIGN_KEY: ${{secrets.COSIGN_KEY}}
+      #     COSIGN_PASSWORD: ${{secrets.COSIGN_PASSPHRASE}}
 
       - name: Fetch commit details
         run: |
@@ -402,41 +402,41 @@ jobs:
         run: |
           cosign verify-attestation --certificate-github-workflow-name=.github/workflows/cicd.yml@refs/heads/testing --certificate-github-workflow-ref=refs/heads/testing --certificate-github-workflow-repository=https://github.com/sachinmaniyar/spring-petclinic --certificate-github-workflow-trigger=push --key cosign.pub ghcr.io/sachinmaniyar/${{ env.AppName }}:latest | jq -r .payload | base64 --decode | jq .
     
-  Deploy_To_Aks:
-    runs-on: ubuntu-latest
-    needs: Attest_Verify_Predicate
-    env:
-      RESOURCE_GROUP: 'K8SDemo'
-      CLUSTER_NAME: 'K8SDemo'
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
-      - uses: azure/login@v2
-        with:
-          creds: ${{ secrets.AZURE_CREDENTIALS }}
+  # Deploy_To_Aks:
+  #   runs-on: ubuntu-latest
+  #   needs: Attest_Verify_Predicate
+  #   env:
+  #     RESOURCE_GROUP: 'K8SDemo'
+  #     CLUSTER_NAME: 'K8SDemo'
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
+  #     - uses: azure/login@v2
+  #       with:
+  #         creds: ${{ secrets.AZURE_CREDENTIALS }}
 
-      - name: Azure CLI script
-        uses: azure/cli@v2
-        with:
-          azcliversion: latest
-          inlineScript: |
-            az account show
-            # Use kubelogin to configure your kubeconfig for Azure auth
-      - name: Set up kubelogin for non-interactive login
-        uses: azure/use-kubelogin@v1
-        with:
-          kubelogin-version: 'v0.0.25'
+  #     - name: Azure CLI script
+  #       uses: azure/cli@v2
+  #       with:
+  #         azcliversion: latest
+  #         inlineScript: |
+  #           az account show
+  #           # Use kubelogin to configure your kubeconfig for Azure auth
+  #     - name: Set up kubelogin for non-interactive login
+  #       uses: azure/use-kubelogin@v1
+  #       with:
+  #         kubelogin-version: 'v0.0.25'
 
-        # Retrieves your Azure Kubernetes Service cluster's kubeconfig file
-      - name: Get K8s context
-        uses: azure/aks-set-context@v3
-        with:
-          resource-group: ${{ env.RESOURCE_GROUP }}
-          cluster-name: ${{ env.CLUSTER_NAME }}
-          admin: 'false'
-          use-kubelogin: 'true'       
-      - name: Deploy to AKS
-        run: |
-          kubectl apply -f K8s/deployment.yaml
-          kubectl apply -f K8s/service.yaml
+  #       # Retrieves your Azure Kubernetes Service cluster's kubeconfig file
+  #     - name: Get K8s context
+  #       uses: azure/aks-set-context@v3
+  #       with:
+  #         resource-group: ${{ env.RESOURCE_GROUP }}
+  #         cluster-name: ${{ env.CLUSTER_NAME }}
+  #         admin: 'false'
+  #         use-kubelogin: 'true'       
+  #     - name: Deploy to AKS
+  #       run: |
+  #         kubectl apply -f K8s/deployment.yaml
+  #         kubectl apply -f K8s/service.yaml
