Update cicd.yml

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -46,7 +46,6 @@ jobs:
           gh attestation verify app.jar --owner sachinmaniyar --format=json | jq .
   Sonar_And_Sbom_Generation:
     runs-on: ubuntu-latest
-    continue-on-error: true
     env:
       AppName: 'spring-petclinic'
     strategy:
@@ -64,7 +63,8 @@ jobs:
       - name: Set up JDK 17
         uses: actions/setup-java@v1
         with:
-          java-version: 17             
+          java-version: 17          
+      
       - name: Install Syft
         run: |
           curl -sSL https://github.com/anchore/syft/releases/download/v0.66.0/syft_0.66.0_linux_amd64.tar.gz | tar xz -C /usr/local/bin syft
@@ -92,8 +92,6 @@ jobs:
           gh attestation verify ./sbom.json --owner sachinmaniyar --format=json | jq .
   Image_Build_And_Scan:
     runs-on: ubuntu-latest
-    outputs:
-      image: ${{ steps.build.outputs.image }}
     env:
       AppName: 'spring-petclinic'
     steps:    
@@ -116,11 +114,17 @@ jobs:
           #password: ${{secrets.GH_TOKEN}}
           registry: ghcr.io
 
-
+      - name: Tag Docker Image
+        run: |
+          docker tag docker.io/library/${{ env.AppName }}:3.3.0-SNAPSHOT ghcr.io/sachinmaniyar/${{ env.AppName }}:latest
+      - name: Push Docker Image
+        run: |
+          docker push ghcr.io/sachinmaniyar/${{ env.AppName }}:latest
+          docker inspect ghcr.io/sachinmaniyar/${{ env.AppName }}:latest
       - name: Run Trivy Vulnerability Scanner
         uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
         with:
-          image-ref: 'docker.io/library/${{ env.AppName }}:3.3.0-SNAPSHOT'
+          image-ref: 'ghcr.io/sachinmaniyar/${{ env.AppName }}:latest'
           format: 'template'
           template: '@/contrib/sarif.tpl'
           output: 'trivy-results.sarif'
@@ -166,7 +170,7 @@ jobs:
           cosign version
       - name: sign container image
         run: |
-          cosign sign --key env://COSIGN_KEY ${{ needs.build.outputs.image }} --yes
+          cosign sign --key env://COSIGN_KEY ghcr.io/sachinmaniyar/${{ env.AppName }}:latest --yes
         shell: bash
         env:
           COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
@@ -182,13 +186,14 @@ jobs:
         
       - name: Verify Docker Image Signature
         run: |
-          cosign verify --key cosign.pub ${{ needs.build.outputs.image }} | jq . #--insecure-ignore-tlog #--check-claims=false
+          docker inspect ghcr.io/sachinmaniyar/${{ env.AppName }}:latest
+          cosign verify --key cosign.pub ghcr.io/sachinmaniyar/${{ env.AppName }}:latest | jq . #--insecure-ignore-tlog #--check-claims=false
       - name: Attach SBOM
         id: attach-sbom
         run: |
           set -e  # Exit on error
           # Run the cosign attach sbom command and capture its output
-          output=$(cosign attach sbom --sbom sbom.json ${{ needs.build.outputs.image }} 2>&1) || { echo "Failed to run cosign attach sbom"; exit 1; }
+          output=$(cosign attach sbom --sbom sbom.json ghcr.io/sachinmaniyar/${{ env.AppName }}:latest 2>&1) || { echo "Failed to run cosign attach sbom"; exit 1; }
           echo "cat output --> showing output below"
           echo "output: $output"
           # Extract the SHA from the output
@@ -219,13 +224,14 @@ jobs:
 
       - name: Verify Sign of SBOM attached with the Image
         run: |
+          docker inspect ghcr.io/sachinmaniyar/${{ env.AppName }}:latest
           set -e  # Exit on error
           cosign verify --key cosign.pub ghcr.io/sachinmaniyar/${{ env.AppName }}:$SBOM_FILENAME | jq . || { echo "Failed to verify SBOM Sign"; exit 1; }
       - name: Directly attest SBOM with the Image
         run: |
           set -e  # Exit on error
-          # output=$(cosign attest --key env://COSIGN_KEY --type cyclonedx --predicate sbom.json ${{ needs.build.outputs.image }} --yes 2>&1) || { echo "Failed to attest sbom with the image"; exit 1; }
-          output=$(cosign attest --key env://COSIGN_KEY --predicate sbom.json ${{ needs.build.outputs.image }} --yes 2>&1) || { echo "Failed to attest sbom with the image"; exit 1; }
+          # output=$(cosign attest --key env://COSIGN_KEY --type cyclonedx --predicate sbom.json ghcr.io/sachinmaniyar/${{ env.AppName }}:latest --yes 2>&1) || { echo "Failed to attest sbom with the image"; exit 1; }
+          output=$(cosign attest --key env://COSIGN_KEY --predicate sbom.json ghcr.io/sachinmaniyar/${{ env.AppName }}:latest --yes 2>&1) || { echo "Failed to attest sbom with the image"; exit 1; }
           echo "output: $output"
         shell: bash
 
@@ -237,8 +243,9 @@ jobs:
       - name: Verfiy the attested Image
         run: |
           set -e  # Exit on error
-          # output1=$(cosign verify-attestation --key cosign.pub ${{ needs.build.outputs.image }} | jq -r .payload | base64 -D | jq . 2>&1) || { echo "Failed to verify the attested image"; exit 1; }
-          output1=$(cosign verify-attestation --key cosign.pub ${{ needs.build.outputs.image }} | jq . 2>&1) || { echo "Failed to verify the attested image"; exit 1; }
+          docker inspect ghcr.io/sachinmaniyar/${{ env.AppName }}:latest
+          # output1=$(cosign verify-attestation --key cosign.pub ghcr.io/sachinmaniyar/${{ env.AppName }}:latest | jq -r .payload | base64 -D | jq . 2>&1) || { echo "Failed to verify the attested image"; exit 1; }
+          output1=$(cosign verify-attestation --key cosign.pub ghcr.io/sachinmaniyar/${{ env.AppName }}:latest | jq . 2>&1) || { echo "Failed to verify the attested image"; exit 1; }
           echo "output: $output1"
       - name: Sign SBOM
         run: |
@@ -252,12 +259,13 @@ jobs:
       - name: upload Signed SBOM to Github Registry
         run: |
           # set -e  # Exit on error
-          output2=$(cosign upload blob -f cosign.bundle ${{ needs.build.outputs.image }} 2>&1) #| jq .) #|| { echo "Failed to upload the blob to the Registry"; exit 1; }
+          output2=$(cosign upload blob -f cosign.bundle ghcr.io/sachinmaniyar/${{ env.AppName }}:latest 2>&1) #| jq .) #|| { echo "Failed to upload the blob to the Registry"; exit 1; }
           echo "output: $output2"
           sbom_file=$(echo "$output2" | grep -oP 'sha256:[\w\d]{64}' | head -n 1) || { echo "Failed to extract SBOM filename"; exit 1; }
           echo "sbom_file: $sbom_file"
       - name: Verify SBOM Uploaded to Image Repo
         run: |
+          docker inspect ghcr.io/sachinmaniyar/${{ env.AppName }}:latest
           cosign verify-blob sbom.json --bundle cosign.bundle --certificate-github-workflow-name=.github/workflows/cicd.yml@refs/heads/testing --certificate-github-workflow-ref=refs/heads/main --certificate-github-workflow-repository=https://github.com/sachinmaniyar/${{ env.AppName }} --certificate-github-workflow-trigger=push --key cosign.pub 2>&1 #| jq -r .payload | base64 --decode | jq .
         shell: bash
         env:
@@ -304,44 +312,44 @@ jobs:
         with:
           name: git-details
           path: output.json
-  Sbom_Upload:
-    runs-on: ubuntu-latest
-    needs: Sonar_And_Sbom_Generation
-    steps:
-      - name: Check Out Source Code
-        uses: actions/checkout@v3     
-      - name: Download file artifact
-        uses: actions/download-artifact@v4
-        with:
-          name: sbom
-      - name: Download shell script from Gist
-        run: |
-          cat sbom.json 
-          curl -o project_creation_sbom_upload.sh https://gist.githubusercontent.com/SachinManiyar/20e5a000b24e257181228c6b3c46c004/raw/755ef0f37f0edcaa93464713daf2866a8dadcc1d/project_creation_sbom_upload.sh
-      - name: Make the script executable
-        run: chmod +x project_creation_sbom_upload.sh
+  # Sbom_Upload:
+  #   runs-on: ubuntu-latest
+  #   needs: Sonar_And_Sbom_Generation
+  #   steps:
+  #     - name: Check Out Source Code
+  #       uses: actions/checkout@v3     
+  #     - name: Download file artifact
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: sbom
+  #     - name: Download shell script from Gist
+  #       run: |
+  #         cat sbom.json 
+  #         curl -o project_creation_sbom_upload.sh https://gist.githubusercontent.com/SachinManiyar/20e5a000b24e257181228c6b3c46c004/raw/755ef0f37f0edcaa93464713daf2866a8dadcc1d/project_creation_sbom_upload.sh
+  #     - name: Make the script executable
+  #       run: chmod +x project_creation_sbom_upload.sh
 
-      - name: Run the shell script
-        run: ./project_creation_sbom_upload.sh -u ${{ secrets.URL_SCORE }} -t ${{ secrets.T_SCORE }} -p ${{ secrets.P_SCORE }} -v ${{ secrets.V_SCORE }}
+  #     - name: Run the shell script
+  #       run: ./project_creation_sbom_upload.sh -u ${{ secrets.URL_SCORE }} -t ${{ secrets.T_SCORE }} -p ${{ secrets.P_SCORE }} -v ${{ secrets.V_SCORE }}
  
-  vulnerability_score:
-    runs-on: ubuntu-latest
-    needs: Sbom_Upload
-    #if: false
-    steps:
-      - name: Check Out Source Code
-        uses: actions/checkout@v3     
-      - name: Checkout code
-        uses: actions/checkout@v3
+  # vulnerability_score:
+  #   runs-on: ubuntu-latest
+  #   needs: Sbom_Upload
+  #   #if: false
+  #   steps:
+  #     - name: Check Out Source Code
+  #       uses: actions/checkout@v3     
+  #     - name: Checkout code
+  #       uses: actions/checkout@v3
       
-      - name: Download shell script from Gist
-        run: |
-          curl -o vulnerability_score.sh https://gist.githubusercontent.com/SachinManiyar/50c889020f611cc0e2bad3543396992a/raw/b13972079aa046ffc7ecbc4e49c9888d107718e6/vulnerability_score.sh
-      - name: Make the script executable
-        run: chmod +x vulnerability_score.sh
+  #     - name: Download shell script from Gist
+  #       run: |
+  #         curl -o vulnerability_score.sh https://gist.githubusercontent.com/SachinManiyar/50c889020f611cc0e2bad3543396992a/raw/b13972079aa046ffc7ecbc4e49c9888d107718e6/vulnerability_score.sh
+  #     - name: Make the script executable
+  #       run: chmod +x vulnerability_score.sh
 
-      - name: Run the shell script
-        run: ./vulnerability_score.sh -u ${{ secrets.URL_SCORE }} -t ${{ secrets.T_SCORE }} -p ${{ secrets.P_SCORE }} -d ${{ secrets.D_SCORE }} -v ${{ secrets.V_SCORE }}
+  #     - name: Run the shell script
+  #       run: ./vulnerability_score.sh -u ${{ secrets.URL_SCORE }} -t ${{ secrets.T_SCORE }} -p ${{ secrets.P_SCORE }} -d ${{ secrets.D_SCORE }} -v ${{ secrets.V_SCORE }}
    
   Attest_Verify_Predicate:
     permissions:
@@ -387,9 +395,9 @@ jobs:
 
       - name: Attestation using Predicate
         run: |
-          cosign attest --key env://COSIGN_KEY --predicate output.json ${{ needs.build.outputs.image }} --yes
-          # $(cosign attest --key env://COSIGN_KEY --predicate output.json ${{ needs.build.outputs.image }} --yes 2>&1) || { echo "Failed to attest predicate with the image"; exit 1; }
-          # $(cat output.json | cosign attest --predicate - ${{ needs.build.outputs.image }} --yes 2>&1) || { echo "Failed to attest predicate with the image"; exit 1; }
+          cosign attest --key env://COSIGN_KEY --predicate output.json ghcr.io/sachinmaniyar/${{ env.AppName }}:latest --yes
+          # $(cosign attest --key env://COSIGN_KEY --predicate output.json ghcr.io/sachinmaniyar/${{ env.AppName }}:latest --yes 2>&1) || { echo "Failed to attest predicate with the image"; exit 1; }
+          # $(cat output.json | cosign attest --predicate - ghcr.io/sachinmaniyar/${{ env.AppName }}:latest --yes 2>&1) || { echo "Failed to attest predicate with the image"; exit 1; }
         shell: bash
         env:
           COSIGN_KEY: ${{secrets.COSIGN_KEY}}
@@ -397,38 +405,12 @@ jobs:
         
       - name: Verify Predicate Attestation
         run: |
-          cosign verify-attestation --certificate-github-workflow-name=.github/workflows/cicd.yml@refs/heads/testing --certificate-github-workflow-ref=refs/heads/testing --certificate-github-workflow-repository=https://github.com/sachinmaniyar/spring-petclinic --certificate-github-workflow-trigger=push --key cosign.pub ${{ needs.build.outputs.image }} | jq -r .payload | base64 --decode | jq .
-          # $(cosign verify-attestation --key cosign.pub ${{ needs.build.outputs.image }} 2>&1) || { echo "Failed to verify the attested image"; exit 1; }
-  Push_Image:
-    runs-on: ubuntu-latest
-    needs: Attest_Verify_Predicate
-    env:
-      AppName: 'spring-petclinic'
-    steps:    
-      - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis 
-      - name: Set up JDK 17
-        uses: actions/setup-java@v1
-        with:
-          java-version: 17  
-      - name: Log in to GitHub Container Registry
-        uses: docker/login-action@v2
-        with:
-          username: ${{ secrets.CR_Username }}
-          #username: ${{github.actor}}
-          password: ${{ secrets.CR_Password }}
-          #password: ${{secrets.GH_TOKEN}}
-          registry: ghcr.io  
-      - name: Tag Docker Image
-        run: |
-          docker tag ${{ needs.build.outputs.image }}  ghcr.io/sachinmaniyar/spring-petclinic:latest
-      - name: Push Docker Image
-        run: |
-          docker push ghcr.io/sachinmaniyar/spring-petclinic:latest      
+          docker inspect ghcr.io/sachinmaniyar/${{ env.AppName }}:latest
+          cosign verify-attestation --certificate-github-workflow-name=.github/workflows/cicd.yml@refs/heads/testing --certificate-github-workflow-ref=refs/heads/testing --certificate-github-workflow-repository=https://github.com/sachinmaniyar/spring-petclinic --certificate-github-workflow-trigger=push --key cosign.pub ghcr.io/sachinmaniyar/${{ env.AppName }}:latest | jq -r .payload | base64 --decode | jq .
+          # $(cosign verify-attestation --key cosign.pub ghcr.io/sachinmaniyar/${{ env.AppName }}:latest 2>&1) || { echo "Failed to verify the attested image"; exit 1; }
   Deploy_To_Aks:
     runs-on: ubuntu-latest
-    needs: Push_Image
+    needs: Attest_Verify_Predicate
     env:
       RESOURCE_GROUP: 'K8SDemo'
       CLUSTER_NAME: 'K8SDemo'
@@ -464,4 +446,3 @@ jobs:
         run: |
           kubectl apply -f K8s/deployment.yaml
           kubectl apply -f K8s/service.yaml
-              
