Update final-cicd.yaml

diff --git a/.github/workflows/final-cicd.yaml b/.github/workflows/final-cicd.yaml
--- a/.github/workflows/final-cicd.yaml
+++ b/.github/workflows/final-cicd.yaml
@@ -247,22 +247,10 @@ jobs:
 
      - name: upload Signed SBOM to GitHub
        run: |
-          output2=$(cosign upload blob -f cosign.bundle ghcr.io/dheeman2912/spring-petclinic@${{ env.IMAGE_SHA }} 2>&1)
-    
-          # Print the output for debugging purposes
-          echo "Cosign upload output: $output2"
-    
-          # Extract the SBOM digest from the output
-          sbom_file=$(echo "$output2" | grep -oP 'sha256:[\w\d]{64}' | head -n 1)
-    
-          # Check if sbom_file is empty, meaning extraction failed
-          if [[ -z "$sbom_file" ]]; then
-            echo "Failed to extract SBOM filename from output. Cosign upload may have failed."
-            exit 1
-          fi
-      
-          # Output the extracted SBOM filename for confirmation
-          echo "Extracted sbom_file: $sbom_file"
+          output2=$(cosign upload blob -f cosign.bundle  ghcr.io/dheeman2912/spring-petclinic@${{ env.IMAGE_SHA }} 2>&1) #| jq .) #|| { echo "Failed to upload the blob to the Registry"; exit 1; }
+          echo "output: $output2"
+          sbom_file=$(echo "$output2" | grep -oP 'sha256:[\w\d]{64}' | head -n 1) || { echo "Failed to extract SBOM filename"; exit 1; }
+          echo "sbom_file: $sbom_file"
 
      - name: Verify SBOM Uploaded to Image Repo
        run: |
