Update final-cicd.yaml

diff --git a/.github/workflows/final-cicd.yaml b/.github/workflows/final-cicd.yaml
--- a/.github/workflows/final-cicd.yaml
+++ b/.github/workflows/final-cicd.yaml
@@ -247,10 +247,18 @@ jobs:
 
      - name: upload Signed SBOM to GitHub
        run: |
-          output2=$(cosign upload blob -f cosign.bundle  ghcr.io/dheeman2912/spring-petclinic@${{ env.IMAGE_SHA }} 2>&1) #| jq .) #|| { echo "Failed to upload the blob to the Registry"; exit 1; }
-          echo "output: $output2"
-          sbom_file=$(echo "$output2" | grep -oP 'sha256:[\w\d]{64}' | head -n 1) || { echo "Failed to extract SBOM filename"; exit 1; }
-          echo "sbom_file: $sbom_file"
+        # Upload the signed SBOM
+        output2=$(cosign upload blob -f cosign.bundle ghcr.io/dheeman2912/spring-petclinic@${{ env.IMAGE_SHA }} 2>&1) || { echo "Failed to upload the blob to the Registry"; exit 1; }
+        
+        # Display the output
+        echo "output: $output2"
+        
+        # Extract the SBOM filename
+        sbom_file=$(echo "$output2" | grep -oP 'sha256:[\w\d]{64}' | head -n 1) || { echo "Failed to extract SBOM filename"; exit 1; }
+        
+        # Show the extracted SBOM filename
+        echo "sbom_file: $sbom_file"
+
 
      - name: Verify SBOM Uploaded to Image Repo
        run: |
