Update final-cicd.yaml

diff --git a/.github/workflows/final-cicd.yaml b/.github/workflows/final-cicd.yaml
--- a/.github/workflows/final-cicd.yaml
+++ b/.github/workflows/final-cicd.yaml
@@ -10,7 +10,7 @@ jobs:
   build-and-scan:
     runs-on: ubuntu-latest
     container:
-      image: dheeman29/new_image:v2
+      image:  dheeman29/new_image:v3
       
     permissions:
       security-events: write
@@ -37,12 +37,12 @@ jobs:
       # Step 1: Capture SHA256 ID of the Image
      - name: Capture SHA256 ID of the Image
        run: |          
-          REPO_DIGESTS=$(docker inspect --format='{{.RepoDigests}}'  dheeman29/new_image:v2 ) 
+          REPO_DIGESTS=$(docker inspect --format='{{.RepoDigests}}'   dheeman29/new_image:v3 ) 
           if [ "$REPO_DIGESTS" == "[]" ]; then
               echo "Error: RepoDigests is empty. Cannot retrieve SHA256."
               exit 1
           fi
-          CONTAINER_SHA256=$(docker inspect --format='{{index .RepoDigests 0}}'  dheeman29/new_image:v2 | sed 's/.*@sha256://')
+          CONTAINER_SHA256=$(docker inspect --format='{{index .RepoDigests 0}}'   dheeman29/new_image:v3 | sed 's/.*@sha256://')
           echo "CONTAINER_SHA256=$CONTAINER_SHA256" >> $GITHUB_ENV
 
       # Step 2: Verify Container SHA256 ID        
@@ -61,6 +61,7 @@ jobs:
           pwd
           which java 
           echo $JAVA_HOME
+          mvn -version
           ./mvn -X package > app.jar
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
@@ -313,7 +314,7 @@ jobs:
     env:
       PR_NUMBER: ${{ needs.build-and-scan.outputs.pr-number }}
     # container:      
-    #   image: dheeman29/new-cosign-image:v1
+    #   image:  dheeman29/new_image:v3
 
     permissions:
       security-events: write
@@ -326,12 +327,12 @@ jobs:
       # Step 1: Capture SHA256 ID of the Image
       - name: Capture SHA256 ID of the Image
         run: |          
-          REPO_DIGESTS=$(docker inspect --format='{{.RepoDigests}}' dheeman29/new-cosign-image:v1) 
+          REPO_DIGESTS=$(docker inspect --format='{{.RepoDigests}}'  dheeman29/new_image:v3) 
           if [ "$REPO_DIGESTS" == "[]" ]; then
               echo "Error: RepoDigests is empty. Cannot retrieve SHA256."
               exit 1
           fi
-          CONTAINER_SHA256=$(docker inspect --format='{{index .RepoDigests 0}}' dheeman29/new-cosign-image:v1 | sed 's/.*@sha256://')
+          CONTAINER_SHA256=$(docker inspect --format='{{index .RepoDigests 0}}'  dheeman29/new_image:v3 | sed 's/.*@sha256://')
           echo "CONTAINER_SHA256=$CONTAINER_SHA256" >> $GITHUB_ENV
 
       # Step 2: Verify Container SHA256 ID        
@@ -406,32 +407,32 @@ jobs:
 
   Deploy_To_Aks:
     runs-on: ubuntu-latest
-    # container:
-      # image: dheeman29/new-cosign-image:v1
+    container:
+      image:  dheeman29/new_image:v3
     needs: Attest_Verify_Predicate
     steps:
-      # # Step 1: Capture SHA256 ID of the Image
-      # - name: Capture SHA256 ID of the Image
-      #   run: |          
-      #     REPO_DIGESTS=$(docker inspect --format='{{.RepoDigests}}' dheeman29/new-cosign-image:v1) 
-      #     if [ "$REPO_DIGESTS" == "[]" ]; then
-      #       echo "Error: RepoDigests is empty. Cannot retrieve SHA256."
-      #       exit 1
-      #     fi
-      #     CONTAINER_SHA256=$(docker inspect --format='{{index .RepoDigests 0}}' dheeman29/new-cosign-image:v1| sed 's/.*@sha256://')
-      #     echo "CONTAINER_SHA256=$CONTAINER_SHA256" >> $GITHUB_ENV
+      # Step 1: Capture SHA256 ID of the Image
+      - name: Capture SHA256 ID of the Image
+        run: |          
+          REPO_DIGESTS=$(docker inspect --format='{{.RepoDigests}}'  dheeman29/new_image:v3) 
+          if [ "$REPO_DIGESTS" == "[]" ]; then
+            echo "Error: RepoDigests is empty. Cannot retrieve SHA256."
+            exit 1
+          fi
+          CONTAINER_SHA256=$(docker inspect --format='{{index .RepoDigests 0}}'  dheeman29/new_image:v3| sed 's/.*@sha256://')
+          echo "CONTAINER_SHA256=$CONTAINER_SHA256" >> $GITHUB_ENV
 
-      # # Step 2: Verify Container SHA256 ID        
-      # - name: Verify Container SHA256 ID        
-      #   run: |          
-      #     EXPECTED_SHA256="${{ secrets.EXPECTED_SHA256 }}"
-      #     ACTUAL_SHA256="${{ env.CONTAINER_SHA256 }}"
+      # Step 2: Verify Container SHA256 ID        
+      - name: Verify Container SHA256 ID        
+        run: |          
+          EXPECTED_SHA256="${{ secrets.EXPECTED_SHA256 }}"
+          ACTUAL_SHA256="${{ env.CONTAINER_SHA256 }}"
           
-      #     if [ "$EXPECTED_SHA256" != "$ACTUAL_SHA256" ]; then
-      #       echo "SHA256 mismatch. Aborting."
-      #       exit 1
-      #     fi
-      #     echo "SHA256 ID verified successfully."
+          if [ "$EXPECTED_SHA256" != "$ACTUAL_SHA256" ]; then
+            echo "SHA256 mismatch. Aborting."
+            exit 1
+          fi
+          echo "SHA256 ID verified successfully."
 
       # Step 3: Checkout the code
       - name: Checkout Code
