Update final-cicd.yaml

diff --git a/.github/workflows/final-cicd.yaml b/.github/workflows/final-cicd.yaml
--- a/.github/workflows/final-cicd.yaml
+++ b/.github/workflows/final-cicd.yaml
@@ -61,7 +61,7 @@ jobs:
           pwd
           which java 
           echo $JAVA_HOME
-          ./mvnw -B package > app.jar
+          ./mvn -X package > app.jar
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
@@ -185,83 +185,83 @@ jobs:
        run: |
           cosign verify --key cosign.pub ghcr.io/dheeman2912/spring-petclinic@${{ env.IMAGE_SHA }} | jq . #--insecure-ignore-tlog #--check-claims=false
 
-     # - name: Attach SBOM
-     #   run: |
-     #      set -e  # Exit on error
-     #      # Run the cosign attach sbom command and capture its output
-     #      output=$(cosign attach sbom --sbom sbom.json ghcr.io/dheeman2912/spring-petclinic@${{ env.IMAGE_SHA }}  2>&1) || { echo "Failed to run cosign attach sbom"; exit 1; }
-     #      echo "cat output --> showing output below"
-     #      echo "output: $output"
-     #      # Extract the SHA from the output
-     #      sbom_filename=$(echo "$output" | grep -oP 'sha256-[\w\d]+\.sbom') || { echo "Failed to extract SBOM filename"; exit 1; }
-     #      echo "sbom_filename: $sbom_filename"
-     #      # Check if the extraction was successful
-     #      if [ -z "$sbom_filename" ]; then
-     #        echo "Error: No SBOM filename found in the output"
-     #        exit 1
-     #      fi
-     #      # Set the extracted SHA as an environment variable
-     #      echo "SBOM_FILENAME=$sbom_filename" >> $GITHUB_ENV
+     - name: Attach SBOM
+       run: |
+          set -e  # Exit on error
+          # Run the cosign attach sbom command and capture its output
+          output=$(cosign attach sbom --sbom sbom.json ghcr.io/dheeman2912/spring-petclinic@${{ env.IMAGE_SHA }}  2>&1) || { echo "Failed to run cosign attach sbom"; exit 1; }
+          echo "cat output --> showing output below"
+          echo "output: $output"
+          # Extract the SHA from the output
+          sbom_filename=$(echo "$output" | grep -oP 'sha256-[\w\d]+\.sbom') || { echo "Failed to extract SBOM filename"; exit 1; }
+          echo "sbom_filename: $sbom_filename"
+          # Check if the extraction was successful
+          if [ -z "$sbom_filename" ]; then
+            echo "Error: No SBOM filename found in the output"
+            exit 1
+          fi
+          # Set the extracted SHA as an environment variable
+          echo "SBOM_FILENAME=$sbom_filename" >> $GITHUB_ENV
 
-     # - name: Sign the SBOM attached with the Image
-     #   run: |
-     #      set -e  # Exit on error
-     #      # Use the environment variable to construct the command
-     #      if [ -z "$SBOM_FILENAME" ]; then
-     #        echo "Error: SBOM_FILENAME environment variable is not set"
-     #        exit 1
-     #      fi
-     #      echo "Signing SBOM with filename: $SBOM_FILENAME"
-     #      cosign sign --key env://COSIGN_KEY   ghcr.io/dheeman2912/spring-petclinic:$SBOM_FILENAME --yes || { echo "Failed to sign with SBOM"; exit 1; }
-     #   shell: bash
-     #   env:
-     #      COSIGN_KEY: ${{secrets.COSIGN_KEY}}
-     #      COSIGN_PASSWORD: ${{secrets.COSIGN_PASSPHRASE}}
+     - name: Sign the SBOM attached with the Image
+       run: |
+          set -e  # Exit on error
+          # Use the environment variable to construct the command
+          if [ -z "$SBOM_FILENAME" ]; then
+            echo "Error: SBOM_FILENAME environment variable is not set"
+            exit 1
+          fi
+          echo "Signing SBOM with filename: $SBOM_FILENAME"
+          cosign sign --key env://COSIGN_KEY   ghcr.io/dheeman2912/spring-petclinic:$SBOM_FILENAME --yes || { echo "Failed to sign with SBOM"; exit 1; }
+       shell: bash
+       env:
+          COSIGN_KEY: ${{secrets.COSIGN_KEY}}
+          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSPHRASE}}
 
-     # - name: Verify Sign of SBOM attached with the Image
-     #   run: |
-     #      set -e  # Exit on error
-     #      cosign verify --key cosign.pub ghcr.io/dheeman2912/spring-petclinic:$SBOM_FILENAME | jq . || { echo "Failed to verify SBOM Sign"; exit 1; }
+     - name: Verify Sign of SBOM attached with the Image
+       run: |
+          set -e  # Exit on error
+          cosign verify --key cosign.pub ghcr.io/dheeman2912/spring-petclinic:$SBOM_FILENAME | jq . || { echo "Failed to verify SBOM Sign"; exit 1; }
 
-     # - name: Directly attest SBOM with the Image
-     #   run: |
-     #      set -e  # Exit on error
-     #      output=$(cosign attest --key env://COSIGN_KEY --predicate sbom.json ghcr.io/dheeman2912/spring-petclinic@${{ env.IMAGE_SHA }}  --yes 2>&1) || { echo "Failed to attest sbom with the image"; exit 1; }
-     #      echo "output: $output"
-     #   shell: bash
-     #   env:
-     #      COSIGN_KEY: ${{secrets.COSIGN_KEY}}
-     #      COSIGN_PASSWORD: ${{secrets.COSIGN_PASSPHRASE}}
+     - name: Directly attest SBOM with the Image
+       run: |
+          set -e  # Exit on error
+          output=$(cosign attest --key env://COSIGN_KEY --predicate sbom.json ghcr.io/dheeman2912/spring-petclinic@${{ env.IMAGE_SHA }}  --yes 2>&1) || { echo "Failed to attest sbom with the image"; exit 1; }
+          echo "output: $output"
+       shell: bash
+       env:
+          COSIGN_KEY: ${{secrets.COSIGN_KEY}}
+          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSPHRASE}}
 
-     # - name: Verfiy the attested Image
-     #   run: |
-     #      set -e  # Exit on error
-     #      output1=$(cosign verify-attestation --key cosign.pub ghcr.io/dheeman2912/spring-petclinic@${{ env.IMAGE_SHA }}  | jq . 2>&1) || { echo "Failed to verify the attested image"; exit 1; }
-     #      echo "output: $output1"
+     - name: Verfiy the attested Image
+       run: |
+          set -e  # Exit on error
+          output1=$(cosign verify-attestation --key cosign.pub ghcr.io/dheeman2912/spring-petclinic@${{ env.IMAGE_SHA }}  | jq . 2>&1) || { echo "Failed to verify the attested image"; exit 1; }
+          echo "output: $output1"
 
-     # # - name: Sign SBOM
-     # #   run: |
-     # #      cosign sign-blob --yes --key env://COSIGN_KEY sbom.json --bundle cosign.bundle 2>&1
-     # #   shell: bash
-     # #   env:
-     # #      COSIGN_KEY: ${{secrets.COSIGN_KEY}}
-     # #      COSIGN_PASSWORD: ${{secrets.COSIGN_PASSPHRASE}}
+     - name: Sign SBOM
+       run: |
+          cosign sign-blob --yes --key env://COSIGN_KEY sbom.json --bundle cosign.bundle 2>&1
+       shell: bash
+       env:
+          COSIGN_KEY: ${{secrets.COSIGN_KEY}}
+          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSPHRASE}}
 
-     # - name: upload Signed SBOM to GitHub
-     #   run: |
-     #    output2=$(cosign upload blob -f cosign.bundle ghcr.io/dheeman2912/spring-petclinic@${{ env.IMAGE_SHA }} 2>&1) || { echo "Failed to upload the blob to the Registry"; exit 1; }
-     #    echo "output: $output2"
-     #    sbom_file=$(echo "$output2" | grep -oP 'sha256:[\w\d]{64}' | head -n 1) || { echo "Failed to extract SBOM filename"; exit 1; }
-     #    echo "sbom_file: $sbom_file"
+     - name: upload Signed SBOM to GitHub
+       run: |
+        output2=$(cosign upload blob -f cosign.bundle ghcr.io/dheeman2912/spring-petclinic@${{ env.IMAGE_SHA }} 2>&1) || { echo "Failed to upload the blob to the Registry"; exit 1; }
+        echo "output: $output2"
+        sbom_file=$(echo "$output2" | grep -oP 'sha256:[\w\d]{64}' | head -n 1) || { echo "Failed to extract SBOM filename"; exit 1; }
+        echo "sbom_file: $sbom_file"
 
 
-     # - name: Verify SBOM Uploaded to Image Repo
-     #   run: |
-     #      cosign verify-blob sbom.json --bundle cosign.bundle --certificate-github-workflow-name=.github/workflows/cicd.yml@refs/heads/testing --certificate-github-workflow-ref=refs/heads/main --certificate-github-workflow-repository=https://github.com/dheeman2912/spring-petclinic --certificate-github-workflow-trigger=push --key cosign.pub 2>&1
-     #   shell: bash
-     #   env:
-     #      COSIGN_KEY: ${{secrets.COSIGN_KEY}}
-     #      COSIGN_PASSWORD: ${{secrets.COSIGN_PASSPHRASE}}
+     - name: Verify SBOM Uploaded to Image Repo
+       run: |
+          cosign verify-blob sbom.json --bundle cosign.bundle --certificate-github-workflow-name=.github/workflows/cicd.yml@refs/heads/testing --certificate-github-workflow-ref=refs/heads/main --certificate-github-workflow-repository=https://github.com/dheeman2912/spring-petclinic --certificate-github-workflow-trigger=push --key cosign.pub 2>&1
+       shell: bash
+       env:
+          COSIGN_KEY: ${{secrets.COSIGN_KEY}}
+          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSPHRASE}}
 
      - name: Set Git safe directory
        run: git config --global --add safe.directory /__w/spring-petclinic/spring-petclinic
@@ -323,28 +323,28 @@ jobs:
       packages: write
     needs: build-and-scan
     steps:
-      # # Step 1: Capture SHA256 ID of the Image
-      # - name: Capture SHA256 ID of the Image
-      #   run: |          
-      #     REPO_DIGESTS=$(docker inspect --format='{{.RepoDigests}}' dheeman29/new-cosign-image:v1) 
-      #     if [ "$REPO_DIGESTS" == "[]" ]; then
-      #         echo "Error: RepoDigests is empty. Cannot retrieve SHA256."
-      #         exit 1
-      #     fi
-      #     CONTAINER_SHA256=$(docker inspect --format='{{index .RepoDigests 0}}' dheeman29/new-cosign-image:v1 | sed 's/.*@sha256://')
-      #     echo "CONTAINER_SHA256=$CONTAINER_SHA256" >> $GITHUB_ENV
+      # Step 1: Capture SHA256 ID of the Image
+      - name: Capture SHA256 ID of the Image
+        run: |          
+          REPO_DIGESTS=$(docker inspect --format='{{.RepoDigests}}' dheeman29/new-cosign-image:v1) 
+          if [ "$REPO_DIGESTS" == "[]" ]; then
+              echo "Error: RepoDigests is empty. Cannot retrieve SHA256."
+              exit 1
+          fi
+          CONTAINER_SHA256=$(docker inspect --format='{{index .RepoDigests 0}}' dheeman29/new-cosign-image:v1 | sed 's/.*@sha256://')
+          echo "CONTAINER_SHA256=$CONTAINER_SHA256" >> $GITHUB_ENV
 
-      # # Step 2: Verify Container SHA256 ID        
-      # - name: Verify Container SHA256 ID        
-      #   run: |          
-      #     EXPECTED_SHA256="${{ secrets.EXPECTED_SHA256 }}"
-      #     ACTUAL_SHA256="${{ env.CONTAINER_SHA256 }}"
+      # Step 2: Verify Container SHA256 ID        
+      - name: Verify Container SHA256 ID        
+        run: |          
+          EXPECTED_SHA256="${{ secrets.EXPECTED_SHA256 }}"
+          ACTUAL_SHA256="${{ env.CONTAINER_SHA256 }}"
           
-      #     if [ "$EXPECTED_SHA256" != "$ACTUAL_SHA256" ]; then
-      #         echo "SHA256 mismatch. Aborting."
-      #         exit 1
-      #     fi
-      #     echo "SHA256 ID verified successfully."
+          if [ "$EXPECTED_SHA256" != "$ACTUAL_SHA256" ]; then
+              echo "SHA256 mismatch. Aborting."
+              exit 1
+          fi
+          echo "SHA256 ID verified successfully."
 
      
       - name: Check Out Source Code
