Update New.yaml

diff --git a/.github/workflows/New.yaml b/.github/workflows/New.yaml
--- a/.github/workflows/New.yaml
+++ b/.github/workflows/New.yaml
@@ -284,40 +284,6 @@ jobs:
           name: git-details
           path: output.json
           
-      - name:  Sbom_Upload
-      - name: Check Out Source Code
-        uses: actions/checkout@v3     
-      - name: Download file artifact
-        uses: actions/download-artifact@v4
-        with:
-         name: sbom
-      - name: Download shell script from Gist
-        run: |
-           cat sbom.json 
-           curl -o project_creation_sbom_upload.sh https://gist.githubusercontent.com/DHEEMAN2912/20e5a000b24e257181228c6b3c46c004/raw/755ef0f37f0edcaa93464713daf2866a8dadcc1d/project_creation_sbom_upload.sh     - name: Make the script executable
-           run: chmod +x project_creation_sbom_upload.sh
-
-      - name: Run the shell script
-        run: ./project_creation_sbom_upload.sh -u ${{ secrets.URL_SCORE }} -t ${{ secrets.T_SCORE }} -p ${{ secrets.P_SCORE }} -v ${{ secrets.V_SCORE }}
-
-      - name: vulnerability_score
-      - name: Check Out Source Code
-        uses: actions/checkout@v3     
-      - name: Checkout code
-        uses: actions/checkout@v3
-      
-      - name: Download shell script from Gist
-         run:|
-          curl -o vulnerability_score.sh https://gist.githubusercontent.com/SachinManiyar/50c889020f611cc0e2bad3543396992a/raw/b13972079aa046ffc7ecbc4e49c9888d107718e6/vulnerability_score.sh
-      - name: Make the script executable
-        run: chmod +x vulnerability_score.sh
-
-      - name: Run the shell script
-        run: ./vulnerability_score.sh -u ${{ secrets.URL_SCORE }} -t ${{ secrets.T_SCORE }} -p ${{ secrets.P_SCORE }} -d ${{ secrets.D_SCORE }} -v ${{ secrets.V_SCORE }}
-
-    
-
-
       
       - name:  Attest_Verify_Predicate
       - name: Check Out Source Code
@@ -333,31 +299,31 @@ jobs:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_PASSWORD }}
 
-      # - name: Install Cosign CLI
-      #   run: |
-      #     curl -sSL -o /usr/local/bin/cosign https://github.com/sigstore/cosign/releases/download/v2.2.3/cosign-linux-amd64
-      #     chmod +x /usr/local/bin/cosign
-      #     cosign version
+      - name: Install Cosign CLI
+        run: |
+          curl -sSL -o /usr/local/bin/cosign https://github.com/sigstore/cosign/releases/download/v2.2.3/cosign-linux-amd64
+          chmod +x /usr/local/bin/cosign
+          cosign version
 
 
-      # - name: Public Key Creation
-      #   run: |
-      #     cosign public-key --key env://COSIGN_KEY > cosign.pub
-      #   shell: bash
-      #   env:
-      #     COSIGN_KEY: ${{secrets.COSIGN_KEY}}
-      #     COSIGN_PASSWORD: ${{secrets.COSIGN_PASSPHRASE}}
+      - name: Public Key Creation
+        run: |
+          cosign public-key --key env://COSIGN_KEY > cosign.pub
+        shell: bash
+        env:
+          COSIGN_KEY: ${{secrets.COSIGN_KEY}}
+          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSPHRASE}}
 
-      # - name: Attestation using Predicate
-      #   run: |
-      #     cosign attest --key env://COSIGN_KEY --predicate output.json docker.io/dheeman29/spring-petclinic:latest --yes
-      #     # $(cosign attest --key env://COSIGN_KEY --predicate output.json docker.io/dheeman29/spring-petclinic:latest --yes 2>&1) || { echo "Failed to attest predicate with the image"; exit 1; }
-      #     # $(cat output.json | cosign attest --predicate - docker.io/dheeman29/spring-petclinic:latest --yes 2>&1) || { echo "Failed to attest predicate with the image"; exit 1; }
-      #   shell: bash
-      #   env:
-      #     COSIGN_KEY: ${{secrets.COSIGN_KEY}}
-      #     COSIGN_PASSWORD: ${{secrets.COSIGN_PASSPHRASE}}
+      - name: Attestation using Predicate
+        run: |
+          cosign attest --key env://COSIGN_KEY --predicate output.json docker.io/dheeman29/spring-petclinic:latest --yes
+          # $(cosign attest --key env://COSIGN_KEY --predicate output.json docker.io/dheeman29/spring-petclinic:latest --yes 2>&1) || { echo "Failed to attest predicate with the image"; exit 1; }
+          # $(cat output.json | cosign attest --predicate - docker.io/dheeman29/spring-petclinic:latest --yes 2>&1) || { echo "Failed to attest predicate with the image"; exit 1; }
+        shell: bash
+        env:
+          COSIGN_KEY: ${{secrets.COSIGN_KEY}}
+          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSPHRASE}}
 
-      # - name: Verify Predicate Attestation
-      #   run: |
-      #     cosign verify-attestation --certificate-github-workflow-name=.github/workflows/cicd.yml@refs/heads/testing --certificate-github-workflow-ref=refs/heads/testing --certificate-github-workflow-repository=https://github.com/dheeman2912/spring-petclinic --certificate-github-workflow-trigger=push --key cosign.pub docker.io/dheeman29/spring-petclinic:latest | jq -r .payload | base64 --decode | jq .
+      - name: Verify Predicate Attestation
+        run: |
+          cosign verify-attestation --certificate-github-workflow-name=.github/workflows/cicd.yml@refs/heads/testing --certificate-github-workflow-ref=refs/heads/testing --certificate-github-workflow-repository=https://github.com/dheeman2912/spring-petclinic --certificate-github-workflow-trigger=push --key cosign.pub docker.io/dheeman29/spring-petclinic:latest | jq -r .payload | base64 --decode | jq .
