Update New.yaml

diff --git a/.github/workflows/New.yaml b/.github/workflows/New.yaml
--- a/.github/workflows/New.yaml
+++ b/.github/workflows/New.yaml
@@ -319,45 +319,45 @@ jobs:
 
 
       
-      # - name:  Attest_Verify_Predicate
-      # - name: Check Out Source Code
-      #   uses: actions/checkout@v3
-      # - name: Download output.json file artifact
-      #   uses: actions/download-artifact@v3
-      #   with:
-      #     name: git-details
+      - name:  Attest_Verify_Predicate
+      - name: Check Out Source Code
+        uses: actions/checkout@v3
+      - name: Download output.json file artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: git-details
 
-      # - name: Log in to Docker Hub
-      #   uses: docker/login-action@v2
-      #   with:
-      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
-      #     password: ${{ secrets.DOCKERHUB_PASSWORD }}
+      - name: Log in to Docker Hub
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_PASSWORD }}
 
-      # - name: Install Cosign CLI
-      #   run: |
-      #     curl -sSL -o /usr/local/bin/cosign https://github.com/sigstore/cosign/releases/download/v2.2.3/cosign-linux-amd64
-      #     chmod +x /usr/local/bin/cosign
-      #     cosign version
+      - name: Install Cosign CLI
+        run: |
+          curl -sSL -o /usr/local/bin/cosign https://github.com/sigstore/cosign/releases/download/v2.2.3/cosign-linux-amd64
+          chmod +x /usr/local/bin/cosign
+          cosign version
 
 
-      # - name: Public Key Creation
-      #   run: |
-      #     cosign public-key --key env://COSIGN_KEY > cosign.pub
-      #   shell: bash
-      #   env:
-      #     COSIGN_KEY: ${{secrets.COSIGN_KEY}}
-      #     COSIGN_PASSWORD: ${{secrets.COSIGN_PASSPHRASE}}
+      - name: Public Key Creation
+        run: |
+          cosign public-key --key env://COSIGN_KEY > cosign.pub
+        shell: bash
+        env:
+          COSIGN_KEY: ${{secrets.COSIGN_KEY}}
+          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSPHRASE}}
 
-      # - name: Attestation using Predicate
-      #   run: |
-      #     cosign attest --key env://COSIGN_KEY --predicate output.json docker.io/dheeman29/spring-petclinic:latest --yes
-      #     # $(cosign attest --key env://COSIGN_KEY --predicate output.json docker.io/dheeman29/spring-petclinic:latest --yes 2>&1) || { echo "Failed to attest predicate with the image"; exit 1; }
-      #     # $(cat output.json | cosign attest --predicate - docker.io/dheeman29/spring-petclinic:latest --yes 2>&1) || { echo "Failed to attest predicate with the image"; exit 1; }
-      #   shell: bash
-      #   env:
-      #     COSIGN_KEY: ${{secrets.COSIGN_KEY}}
-      #     COSIGN_PASSWORD: ${{secrets.COSIGN_PASSPHRASE}}
+      - name: Attestation using Predicate
+        run: |
+          cosign attest --key env://COSIGN_KEY --predicate output.json docker.io/dheeman29/spring-petclinic:latest --yes
+          # $(cosign attest --key env://COSIGN_KEY --predicate output.json docker.io/dheeman29/spring-petclinic:latest --yes 2>&1) || { echo "Failed to attest predicate with the image"; exit 1; }
+          # $(cat output.json | cosign attest --predicate - docker.io/dheeman29/spring-petclinic:latest --yes 2>&1) || { echo "Failed to attest predicate with the image"; exit 1; }
+        shell: bash
+        env:
+          COSIGN_KEY: ${{secrets.COSIGN_KEY}}
+          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSPHRASE}}
 
-      # - name: Verify Predicate Attestation
-      #   run: |
-      #     cosign verify-attestation --certificate-github-workflow-name=.github/workflows/cicd.yml@refs/heads/testing --certificate-github-workflow-ref=refs/heads/testing --certificate-github-workflow-repository=https://github.com/dheeman2912/spring-petclinic --certificate-github-workflow-trigger=push --key cosign.pub docker.io/dheeman29/spring-petclinic:latest | jq -r .payload | base64 --decode | jq .
+      - name: Verify Predicate Attestation
+        run: |
+          cosign verify-attestation --certificate-github-workflow-name=.github/workflows/cicd.yml@refs/heads/testing --certificate-github-workflow-ref=refs/heads/testing --certificate-github-workflow-repository=https://github.com/dheeman2912/spring-petclinic --certificate-github-workflow-trigger=push --key cosign.pub docker.io/dheeman29/spring-petclinic:latest | jq -r .payload | base64 --decode | jq .
