Update testing.yaml

diff --git a/.github/workflows/testing.yaml b/.github/workflows/testing.yaml
--- a/.github/workflows/testing.yaml
+++ b/.github/workflows/testing.yaml
@@ -479,6 +479,32 @@ jobs:
           exit 1
          fi
 
+     - name: Post Deployment Health Check
+       run: |
+        echo "Checking the status of the deployed deployment..."
+        if kubectl rollout status deployment/deployment.yaml; then
+          echo "Deployment is ready."
+        else
+          echo "Error: Deployment is not ready."
+          exit 1
+        fi
+    
+        echo "Checking the status of the service..."
+        if kubectl get svc service.yaml; then
+          echo "Service is available."
+        else
+          echo "Error: Service is not available."
+          exit 1
+        fi
+    
+        echo "Checking if all pods are running..."
+        if kubectl get pods | grep -v 'Running'; then
+          echo "Some pods are not running successfully."
+          exit 1
+        else
+          echo "All pods are running successfully."
+        fi
+
 
   #     - name: Download artifact
   #       uses: actions/download-artifact@v3
