Update testing.yaml

diff --git a/.github/workflows/testing.yaml b/.github/workflows/testing.yaml
--- a/.github/workflows/testing.yaml
+++ b/.github/workflows/testing.yaml
@@ -263,22 +263,6 @@ jobs:
         COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
         COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSPHRASE }}
 
-        
-     # Step 13: Attach SBOM
-     # - name: Attach SBOM
-     #   id: attach_sbom
-     #   run: |
-     #      set -e
-     #      output=$(cosign attach sbom --sbom sbom.json ${{ secrets.IMAGE_NAME }}@${{ steps.get_image_sha.outputs.image_sha }} 2>&1) || { echo "Error: Failed to run cosign attach sbom"; exit 1; }
-     #      echo "cat output --> showing output below"
-     #      echo "output: $output"
-     #      sbom_filename=$(echo "$output" | grep -oP 'sha256-[\w\d]+\.sbom') || { echo "Error: Failed to extract SBOM filename"; exit 1; }
-     #      if [ -z "$sbom_filename" ]; then
-     #        echo "Error: No SBOM filename found in the output"
-     #        exit 1
-     #      fi
-     #      echo "SBOM_FILENAME=$sbom_filename" >> $GITHUB_ENV
-
 
      - name: Attach SBOM with Application Docker Image
        id: attach_sbom
@@ -320,55 +304,73 @@ jobs:
         echo "SBOM_SHA=$sbom_sha" >> $GITHUB_ENV
 
 
-  #    # Step 14: Sign the SBOM attached with the Image
-  #    - name: Sign the SBOM attached with the Image
-  #      id: sign_sbom
-  #      run: |
-  #         set -e
-  #         if [ -z "$SBOM_FILENAME" ]; then
-  #           echo "Error: SBOM_FILENAME environment variable is not set"
-  #           exit 1
-  #         fi
-  #         echo "Signing SBOM with filename: $SBOM_FILENAME"
-  #         cosign sign --key env://COSIGN_KEY ghcr.io/dheeman2912/spring-petclinic:$SBOM_FILENAME --yes || { echo "Error: Failed to sign with SBOM"; exit 1; }
-  #      env:
-  #         COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
-  #         COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSPHRASE }}
+     # Step 14: Sign the SBOM attached with the Image
+     - name: Sign the SBOM attached with the Image
+       id: sign_sbom
+       run: |
+          set -e
+          if [ -z "$SBOM_FILENAME" ]; then
+            echo "Error: SBOM_FILENAME environment variable is not set"
+            exit 1
+          fi
+          echo "Signing SBOM with filename: $SBOM_FILENAME"
+          cosign sign --key env://COSIGN_KEY ${{ secrets.IMAGE_NAME }}:$SBOM_FILENAME --yes && { echo "Success: SBOM created successfully"; } || { echo "Error: Failed to sign with SBOM"; exit 1; }
 
-  #    # Step 15: Verify Sign of SBOM attached with the Image
-  #    - name: Verify Sign of SBOM attached with the Image
-  #      id: verify_sbom_signature
-  #      run: |
-  #         set -e
-  #         cosign verify --key cosign.pub ghcr.io/dheeman2912/spring-petclinic:$SBOM_FILENAME | jq . || { echo "Error: Verification of SBOM signature failed"; exit 1; }
+       env:
+          COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
+          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSPHRASE }}
 
-  #    # Step 16: Directly attest SBOM with the Image
-  #    - name: Directly attest SBOM with the Image
-  #      id: attest_sbom
-  #      run: |
-  #         set -e
-  #         output=$(cosign attest --key env://COSIGN_KEY --predicate sbom.json ghcr.io/dheeman2912/spring-petclinic@${{ env.IMAGE_SHA }} --yes 2>&1) || { echo "Error: Failed to attest SBOM with the image"; exit 1; }
-  #         echo "output: $output"
-  #      env:
-  #         COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
-  #         COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSPHRASE }}
+     # Step 15: Verify Sign of SBOM attached with the Image
+     - name: Verify Sign of SBOM attached with the Image
+       id: verify_sbom_signature
+       run: |
+          set -e
+          cosign verify --key cosign.pub ${{ secrets.IMAGE_NAME }}:$SBOM_FILENAME | jq . || { echo "Error: Verification of SBOM signature failed"; exit 1; }
 
-  #    # Step 17: Verify the attested Image
-  #    - name: Verify the attested Image
-  #      id: verify_attested_image
-  #      run: |
-  #         set -e
-  #         output1=$(cosign verify-attestation --key cosign.pub ghcr.io/dheeman2912/spring-petclinic@${{ env.IMAGE_SHA }} | jq . 2>&1) || { echo "Error: Failed to verify the attested image"; exit 1; }
-  #         echo "output: $output1"
+     # Step 16: Directly attest SBOM with the Image
+     - name: Directly attest SBOM with the Image
+       id: attestt_sbom
+       run: |
+          set -e
+          output=$(cosign attest --key env://COSIGN_KEY --predicate sbom.json ${{ secrets.IMAGE_NAME }}@${{ env.IMAGE_SHA }} --yes 2>&1) || { echo "Error: Failed to attest SBOM with the image"; exit 1; }
+          echo "output: $output"
+       env:
+          COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
+          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSPHRASE }}
 
-  #    # Step 18: Sign SBOM
-  #    - name: Sign SBOM
-  #      id: sign_sbom_blob
-  #      run: |
-  #         cosign sign-blob --yes --key env://COSIGN_KEY sbom.json --bundle cosign.bundle 2>&1 || { echo "Error: Signing SBOM failed"; exit 1; }
-  #      env:
-  #         COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
-  #         COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSPHRASE }}
+     # Step 17: Verify the attested Image
+     - name: Verify the attested Image
+       id: verify_attested_image
+       run: |
+          set -e
+          output1=$(cosign verify-attestation --key cosign.pub ${{ secrets.IMAGE_NAME }}@${{ env.IMAGE_SHA }} | jq . 2>&1) || { echo "Error: Failed to verify the attested image"; exit 1; }
+          echo "output: $output1"
+
+     # Step 18: Sign SBOM
+     - name: Sign SBOM
+       id: sign_sbom_blob
+       run: |
+          cosign sign-blob --yes --key env://COSIGN_KEY sbom.json --bundle cosign.bundle 2>&1 || { echo "Error: Signing SBOM failed"; exit 1; }
+       env:
+          COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
+          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSPHRASE }}
+
+     - name: upload Signed SBOM to Github Registry
+       run: |
+          # set -e  # Exit on error
+          output2=$(cosign upload blob -f cosign.bundle ghcr.io/sachinmaniyar/${{ env.AppName }}:latest 2>&1) #| jq .) #|| { echo "Failed to upload the blob to the Registry"; exit 1; }
+          echo "output: $output2"
+          sbom_file=$(echo "$output2" | grep -oP 'sha256:[\w\d]{64}' | head -n 1) || { echo "Failed to extract SBOM filename"; exit 1; }
+          echo "sbom_file: $sbom_file"
+          
+     - name: Verify SBOM Uploaded to Image Repo
+       run: |
+          
+          cosign verify-blob sbom.json --bundle cosign.bundle --certificate-github-workflow-name=.github/workflows/cicd.yml@refs/heads/testing --certificate-github-workflow-ref=refs/heads/main --certificate-github-workflow-repository=https://github.com/sachinmaniyar/${{ env.AppName }} --certificate-github-workflow-trigger=push --key cosign.pub 2>&1 #| jq -r .payload | base64 --decode | jq .
+       shell: bash
+       env:
+          COSIGN_KEY: ${{secrets.COSIGN_KEY}}
+          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSPHRASE}}
 
   #    # Step 19: Set Git safe directory
   #    - name: Set Git Safe Directory
@@ -432,78 +434,6 @@ jobs:
   #         echo "COMMIT_ID=$COMMIT_ID" >> $GITHUB_ENV
   #         echo "Extracted Commit ID: $COMMIT_ID"  # Debug output to confirm extraction
          
-
-  # Attest_Verify_Predicate:
-  #   runs-on: ubuntu-22.04
-  #   container:      
-  #     image: dheeman29/agent-image:v1
-
-  #   permissions:
-  #     security-events: write
-  #     id-token: write
-  #     contents: read
-  #     attestations: write
-  #     packages: write
-      
-  #   needs: build-and-scan
-    
-  #   steps:
-  #   # Step 1: Capture SHA256 ID of the Image
-  #   - name: Capture SHA256 ID of the Image
-  #     run: |
-  #       REPO_DIGESTS=$(docker inspect --format='{{.RepoDigests}}' dheeman29/agent-image:v1) 
-  #       if [ "$REPO_DIGESTS" == "[]" ]; then
-  #           echo "Error: RepoDigests is empty. Cannot retrieve SHA256."
-  #           exit 1
-  #       fi
-  #       CONTAINER_SHA256=$(docker inspect --format='{{index .RepoDigests 0}}' dheeman29/agent-image:v1 | sed 's/.*@sha256://')
-  #       echo "CONTAINER_SHA256=$CONTAINER_SHA256" >> $GITHUB_ENV
-  #     shell: bash
-
-  #   # Step 2: Verify Container SHA256 ID
-  #   - name: Verify Container SHA256 ID
-  #     run: |
-  #       EXPECTED_SHA256="${{ secrets.EXPECTED_SHA256 }}"
-  #       ACTUAL_SHA256="${{ env.CONTAINER_SHA256 }}"
-
-  #       if [ "$EXPECTED_SHA256" != "$ACTUAL_SHA256" ]; then
-  #           echo "Error: SHA256 mismatch. Aborting."
-  #           exit 1
-  #       fi
-  #       echo "SHA256 ID verified successfully."
-
-  #   # Step 3: Check Out Source Code
-  #   - name: Check Out Source Code
-  #     uses: actions/checkout@v3
-
-  #   # Step 4: Download output.json file artifact
-  #   - name: Download output.json file artifact
-  #     uses: actions/download-artifact@v3
-  #     with:
-  #       name: git-details
-
-  #   # Step 5: Install Tools
-  #   - name: Install Required Tools
-  #     run: |
-  #       chmod +x ./install_dependencies/install_tools.sh
-  #       ./install_dependencies/install_tools.sh || { echo "Error: Tool installation failed"; exit 1; }
-
-  #   # Step 6: Log in to GitHub Container Registry
-  #   - name: Log in to GitHub Container Registry
-  #     uses: docker/login-action@v2
-  #     with:
-  #       username: ${{ secrets.CR_Username }}
-  #       password: ${{ secrets.CR_Password }}
-  #       registry: ghcr.io
-
-  #   # Step 7: Public Key Creation
-  #   - name: Create Public Key for Cosign
-  #     run: |
-  #       cosign public-key --key env://COSIGN_KEY > cosign.pub || { echo "Error: Failed to create public key"; exit 1; }
-  #     shell: bash
-  #     env:
-  #       COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
-  #       COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSPHRASE }}
 
   #   # Step 8: Attestation using Predicate
   #   - name: Attest Image using Predicate
