Update testing.yaml

diff --git a/.github/workflows/testing.yaml b/.github/workflows/testing.yaml
--- a/.github/workflows/testing.yaml
+++ b/.github/workflows/testing.yaml
@@ -352,8 +352,10 @@ jobs:
           
           # Fetch the SBOM SHA from cosign bundle (assuming the SBOM SHA is stored or signed)
           SBOM_SHA=$(cosign upload blob -f cosign.bundle ${{ secrets.IMAGE_NAME }}@${{ env.IMAGE_SHA }} 2>&1 | grep -oP 'sha256:[\w\d]{64}' | head -n 1)
+          
           #Create SBOM link
           SBOM_LINK="https://github.com/dheeman29/spring-petclinic/raw/test/sbom.json"
+          
           # Create JSON output
           OUTPUT=$(jq -n \
             --arg commit_id "$COMMIT_ID" \
@@ -361,6 +363,8 @@ jobs:
             --arg author_email "$AUTHOR_EMAIL" \
             --arg branch "$BRANCH_NAME" \
             --arg uri "$REPO_URL" \
+            --arg sbom_sha "$SBOM_SHA" \
+            --arg sbom_link "$SBOM_LINK" \
             '{
               commit_id: $commit_id,
               git_author_name: $author_name,
@@ -386,96 +390,96 @@ jobs:
         cosign verify-attestation --type https://example.com/CodeReview/v1 --certificate-github-workflow-name=.github/workflows/cicd.yml@refs/heads/testing --certificate-github-workflow-ref=refs/heads/testing --certificate-github-workflow-repository=https://github.com/dheeman2912/spring-petclinic --certificate-github-workflow-trigger=push --key cosign.pub ${{ secrets.IMAGE_NAME }}@${{ env.IMAGE_SHA }} | jq -r .payload | base64 --decode | jq . || { echo "Error: Predicate attestation verification failed"; exit 1; }
        shell: bash
      
-     # - name: Login to Azure
-     #   uses: azure/login@v1
-     #   with:
-     #      creds: ${{ secrets.AZURE_CREDENTIALS }}
-     #      continue-on-error: true
-     # - name: Check Azure Login Status
-     #   run: |
-     #     if [ $? -eq 0 ]; then
-     #      echo "Successfully logged in to Azure."
-     #     else
-     #      echo "Error: Azure login failed."
-     #      exit 1
-     #     fi
-
-     # - name: Verify the AKS Cluster via Managed Identity
-     #   run: |
-     #     CLUSTER_MANAGED_ID=$(az aks show --resource-group ${{ secrets.RESOURCE_GROUP }} --name ${{ secrets.CLUSTER_NAME }} --query identity.principalId --output tsv) || { echo "Failed to fetch Managed Identity"; exit 1; }
-        
-     #     EXPECTED_MANAGED_ID="${{ secrets.EXPECTED_MANAGED_ID }}"
-        
-     #     if [[ "$EXPECTED_MANAGED_ID" != "$CLUSTER_MANAGED_ID" ]]; then
-     #      echo "Error: Managed Identity does not match. Aborting deployment."
-     #      exit 1
-     #     else
-     #      echo "Managed Identity verified successfully."
-     #     fi
-
-     # - name: Download kubeconfig file
-     #   run: |
-     #      if az aks get-credentials --resource-group ${{ secrets.RESOURCE_GROUP }} --name ${{ secrets.CLUSTER_NAME }} --admin --overwrite-existing; then
-     #        echo "Kubeconfig downloaded successfully."
-     #      else
-     #        echo "Error: Failed to download kubeconfig file."
-     #        exit 1
-     #      fi
-
-     # - name: Deploy to AKS
-     #   run: |
-     #     if kubectl apply -f K8s/deployment.yaml; then
-     #      echo "Deployment applied successfully."
-     #     else
-     #      echo "Error deploying application."
-     #      exit 1
-     #     fi
-     #     if kubectl apply -f K8s/service.yaml; then
-     #      echo "Service applied successfully."
-     #     else
-     #      echo "Error deploying service."
-     #      exit 1
-     #     fi
-
-     # - name: Post Deployment Health Check
-     #   run: |
-     #    echo "Checking the status of the deployed deployment..."
-     #    if kubectl get deployment my-app; then
-     #      echo "Deployment is ready."
-     #    else
-     #      echo "Error: Deployment is not ready."
-     #      exit 1
-     #    fi
-    
-     #    echo "Checking the status of the service..."
-     #    if kubectl get svc my-app-service; then
-     #      echo "Service is available."
-     #    else
-     #      echo "Error: Service is not available."
-     #      exit 1
-     #    fi
-    
-
-
-     - name: Download artifact
-       uses: actions/download-artifact@v3
+     - name: Login to Azure
+       uses: azure/login@v1
        with:
-         name: trivy-scan-results
-
-     - name: Send email with artifact
-       env:
-          EMAIL_USER: ${{ secrets.EMAIL_USER }}      # Your email
-          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}      # Your email password or API key
-          RECIPIENTS: dheeman2912@gmail.com  # Comma-separated list of recipients
+          creds: ${{ secrets.AZURE_CREDENTIALS }}
+          continue-on-error: true
+     - name: Check Azure Login Status
        run: |
-          # Ensure the package list is up to date
-          apt-get update
-          # Install mailutils if it's not already installed
-          apt-get install -y mailutils
+         if [ $? -eq 0 ]; then
+          echo "Successfully logged in to Azure."
+         else
+          echo "Error: Azure login failed."
+          exit 1
+         fi
+
+     - name: Verify the AKS Cluster via Managed Identity
+       run: |
+         CLUSTER_MANAGED_ID=$(az aks show --resource-group ${{ secrets.RESOURCE_GROUP }} --name ${{ secrets.CLUSTER_NAME }} --query identity.principalId --output tsv) || { echo "Failed to fetch Managed Identity"; exit 1; }
+        
+         EXPECTED_MANAGED_ID="${{ secrets.EXPECTED_MANAGED_ID }}"
+        
+         if [[ "$EXPECTED_MANAGED_ID" != "$CLUSTER_MANAGED_ID" ]]; then
+          echo "Error: Managed Identity does not match. Aborting deployment."
+          exit 1
+         else
+          echo "Managed Identity verified successfully."
+         fi
+
+     - name: Download kubeconfig file
+       run: |
+          if az aks get-credentials --resource-group ${{ secrets.RESOURCE_GROUP }} --name ${{ secrets.CLUSTER_NAME }} --admin --overwrite-existing; then
+            echo "Kubeconfig downloaded successfully."
+          else
+            echo "Error: Failed to download kubeconfig file."
+            exit 1
+          fi
+
+     - name: Deploy to AKS
+       run: |
+         if kubectl apply -f K8s/deployment.yaml; then
+          echo "Deployment applied successfully."
+         else
+          echo "Error deploying application."
+          exit 1
+         fi
+         if kubectl apply -f K8s/service.yaml; then
+          echo "Service applied successfully."
+         else
+          echo "Error deploying service."
+          exit 1
+         fi
+
+     - name: Post Deployment Health Check
+       run: |
+        echo "Checking the status of the deployed deployment..."
+        if kubectl get deployment my-app; then
+          echo "Deployment is ready."
+        else
+          echo "Error: Deployment is not ready."
+          exit 1
+        fi
+    
+        echo "Checking the status of the service..."
+        if kubectl get svc my-app-service; then
+          echo "Service is available."
+        else
+          echo "Error: Service is not available."
+          exit 1
+        fi
+    
+
+
+     # - name: Download artifact
+     #   uses: actions/download-artifact@v3
+     #   with:
+     #     name: trivy-scan-results
+
+     # - name: Send email with artifact
+     #   env:
+     #      EMAIL_USER: ${{ secrets.EMAIL_USER }}      # Your email
+     #      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}      # Your email password or API key
+     #      RECIPIENTS: dheeman2912@gmail.com  # Comma-separated list of recipients
+     #   run: |
+     #      # Ensure the package list is up to date
+     #      apt-get update
+     #      # Install mailutils if it's not already installed
+     #      apt-get install -y mailutils
       
-          # Create a temporary file for the email content
-          echo "Please find the attached artifact." > email_body.txt
+     #      # Create a temporary file for the email content
+     #      echo "Please find the attached artifact." > email_body.txt
       
-          # Send email with attachment
-          echo "Sending email..."
-          echo "Subject: Artifacts from GitHub Actions" | cat - email_body.txt | mail -s "Artifacts from CI" -a trivy-scan-results/artifact.txt $RECIPIENTS
+     #      # Send email with attachment
+     #      echo "Sending email..."
+     #      echo "Subject: Artifacts from GitHub Actions" | cat - email_body.txt | mail -s "Artifacts from CI" -a trivy-scan-results/artifact.txt $RECIPIENTS
