Update testing.yaml

diff --git a/.github/workflows/testing.yaml b/.github/workflows/testing.yaml
--- a/.github/workflows/testing.yaml
+++ b/.github/workflows/testing.yaml
@@ -238,39 +238,40 @@ jobs:
 
      - name: Inspect Pushed Docker Image by SHA256
        run: |
-        if docker inspect ${{ secrets.IMAGE_NAME }}@sha256:${{ steps.get_image_sha.outputs.IMAGE_SHA }}; then
+        IMAGE_SHA=${{ env.IMAGE_SHA }}
+        if docker inspect "${{ secrets.IMAGE_NAME }}@sha256:$IMAGE_SHA"; then
           echo "Success: Docker image inspected successfully."
         else
           echo "Error: Inspecting Docker image failed."
           exit 1
         fi
      
-     # # Step 10: Sign Docker Image
-     # - name: Sign Docker Image
-     #   id: sign_docker_image
-     #   run: |
-     #      echo "${{ secrets.COSIGN_KEY }}" | tr -d '\r' > cosign.key
-     #      chmod 600 cosign.key
+     # Step 10: Sign Docker Image
+     - name: Sign Docker Image
+       id: sign_docker_image
+       run: |
+          echo "${{ secrets.COSIGN_KEY }}" | tr -d '\r' > cosign.key
+          chmod 600 cosign.key
           
-     #      if cosign sign --key cosign.key ${{ secrets.IMAGE_NAME }}@${{ steps.get_image_sha.outputs.image_sha }} --yes; then
-     #        echo "Success: Docker image signed successfully."
-     #      else
-     #        echo "Error: Signing Docker image failed."
-     #        exit 1
-     #      fi
-     #   env:
-     #      COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSPHRASE }}
+          if cosign sign --key cosign.key ${{ secrets.IMAGE_NAME }}@${{ steps.get_image_sha.outputs.image_sha }} --yes; then
+            echo "Success: Docker image signed successfully."
+          else
+            echo "Error: Signing Docker image failed."
+            exit 1
+          fi
+       env:
+          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSPHRASE }}
 
-     # # Step 11: Public Key Creation
-     # - name: Public Key Creation
-     #   id: create_public_key
-     #   run: |
-     #      if cosign public-key --key ${{ secrets.COSIGN_KEY }} --passphrase ${{ secrets.COSIGN_PASSPHRASE }} > ${{ env.PUBLIC_KEY_FILE }}; then
-     #        echo "Success: Public key created successfully and saved to${{ env.PUBLIC_KEY_FILE }}."
-     #      else
-     #        echo "Error: Public key creation failed."
-     #        exit 1
-     #      f
+     # Step 11: Public Key Creation
+     - name: Public Key Creation
+       id: create_public_key
+       run: |
+          if cosign public-key --key ${{ secrets.COSIGN_KEY }} --passphrase ${{ secrets.COSIGN_PASSPHRASE }} > ${{ env.PUBLIC_KEY_FILE }}; then
+            echo "Success: Public key created successfully and saved to${{ env.PUBLIC_KEY_FILE }}."
+          else
+            echo "Error: Public key creation failed."
+            exit 1
+          fi
         
      # # Step 13: Attach SBOM
      # # - name: Attach SBOM
